[package]
name = "waldo"
version = "0.1.0"
authors = ["aharutyunyan <aharutyunyan@rmn.com>"]

[dependencies]
curl = "0.4"
bson = "0.3"
mongodb = "0.1"
rexiv2 = "0.4"
rotor = "0.6"
rotor-http = "0.7"
xmltree = "0.3"
